src/okslack/main/domain/objects/Slack_for_One_Logger_Setting__mdt/Slack_for_One_Logger_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Configure your Slack messages for One Logger events.</description>
    <label>Slack for One Logger Setting</label>
    <pluralLabel>Slack for One Logger Settings</pluralLabel>
</CustomObject>

src/okslack/main/domain/objects/Slack_for_One_Logger_Setting__mdt/fields/Log_Filter__c.field-meta.xml
<CustomField>
    <fullName>Log_Filter__c</fullName>
    <description>Send Slack message based on the filter.</description>
    <inlineHelpText>Send Slack message based on the filter.</inlineHelpText>
    <label>Log Filter</label>
    <referenceTo>ok__Log_Filter__mdt</referenceTo>
    <relationshipLabel>Slack for One Logger Settings</relationshipLabel>
    <relationshipName>Slack_for_One_Logger_Settings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

src/okslack/main/domain/objects/Slack_for_One_Logger_Setting__mdt/fields/Mention_Here__c.field-meta.xml
<CustomField>
    <fullName>Mention_Here__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Add @here mention.</description>
    <inlineHelpText>Add @here mention.</inlineHelpText>
    <label>Mention Here</label>
    <type>Checkbox</type>
</CustomField>

src/okslack/main/domain/objects/Slack_for_One_Logger_Setting__mdt/fields/Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential__c</fullName>
    <defaultValue>&apos;Slack_for_One_Logger&apos;</defaultValue>
    <description>Named Credential with the Slack webhook. Default is &apos;Slack_for_One_Logger&apos;. Note that Named Credential must be created manually.</description>
    <inlineHelpText>Named Credential with the Slack webhook. Default is &apos;Slack_for_One_Logger&apos;. Note that Named Credential must be created manually.</inlineHelpText>
    <label>Named Credential</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/okslack/main/service/classes/SlackService.cls
/**
 * Service class to send messages from log events.
 */
public inherited sharing class SlackService {
    private static final ok.Logger logger = ok.Logger.getLogger(SlackService.class);
    /**
     * Send Slack messages based on the settings.
     * Each setting represents a one message and a filter criteria for the log events.
     * 
     * @param events the log events
     */
    public void sendMessages(List<ok__Log_Event__e> events) {
        List<SlackSendMessage.Request> requests = new List<SlackSendMessage.Request>();
        ok.LogEvents logEvents = new ok.LogEvents(events);
        SlackForOneLoggerSettings settings = SlackForOneLoggerSettings.load().getActiveSettings();
        Map<Id, List<String>> mentionUserIdsBySettingIds = settings.getMentionUserIdsByIds();
        Map<Id, FieldSet> fieldSetByIds = settings.getLogFieldSetByIds();
        // for each setting send a message if configure correctly
        for (Slack_for_One_Logger_Setting__mdt setting : settings.getSettingList()) {
            FieldSet logFieldSet = fieldSetByIds.get(setting.Id);
            if (logFieldSet == null) {
                logger.error().linkSObject(setting).log('Log Field Set not found.');
                continue;
            }
            List<ok__Log_Event__e> eventsFiltered = logEvents.filter(setting.Log_Filter__c).getLogEventList();
            if (!eventsFiltered.isEmpty()) {
                String endpoint = 'callout:' + setting.Named_Credential__c;
                List<String> mentionUserIds = mentionUserIdsBySettingIds.get(setting.Id);
                SlackMessage message = buildSlackMessage(eventsFiltered, logFieldSet, setting.Mention_Here__c, mentionUserIds);
                requests.add(new SlackSendMessage.Request(endpoint, message));
            }
        }
        new SlackSendMessage().sendAsync(requests);
    }
    /**
     * Construct Slack message based on a setting.
     * 
     * @param logEvents the list of events
     * @param logFieldSet the fields to include
     * @param mentionHere the boolean whether to include here mention
     * @param mentionUserIds the list of Slack user Ids to mention
     *
     * @return the slack message
     */
    private SlackMessage buildSlackMessage(List<ok__Log_Event__e> logEvents, FieldSet logFieldSet, Boolean mentionHere, List<String> mentionUserIds) {
        SlackMessage message = new SlackMessage();
        String headerText = 'Logs from ' + logEvents.get(0).ok__Organization_Name__c;
        message.setText(headerText).createBlockHeader().setPlainText(headerText);
        for (ok__Log_Event__e event : logEvents) {
            List<String> eventTextParts = new List<String>();
            for (FieldSetMember member : logFieldSet.getFields()) {
                String fieldName = String.valueOf(member.getSObjectField());
                String fieldLabel = member.getLabel();
                String fieldValue = String.valueOf(event.get(fieldName));
                eventTextParts.add('*' + fieldLabel + '*: ' + fieldValue);
            }
            if (!eventTextParts.isEmpty()) {
                String eventText = String.join(eventTextParts, '\n');
                message.createBlockSection().setMrkdwn(eventText);
            }
        }
        if (mentionHere != null && mentionHere) {
            SlackMentions mentions = new SlackMentions().mentionHere(mentionHere).addMembers(mentionUserIds);
            message.createBlockSection().setMrkdwn(mentions.toString());
        }
        return message;
    }
}